import { Fn, mat3, vec3 } from "three/tsl"

export const rotateAboutAxis = /*#__PURE__*/ Fn(([pos,axiss,rotateV]) => {
    const inValue =  pos
    const axis =  axiss.normalize()
    const rotateSin =  rotateV.sin()
    const rotateCos =  rotateV.cos()
    const node1 = rotateCos.oneMinus().mul(axis.r) 
    const node2 =  rotateCos.oneMinus().mul(axis.g)
    const node3 =  rotateCos.oneMinus().mul(axis.b)
    const node4 = node1.mul(axis.r)
    const node5 = node1.mul(axis.g)
    const node6 = axis.b.mul(rotateSin)
    const node7 = node1.mul(axis.b)
    const node8 = axis.g.mul(rotateSin)
    const node9 = node2.mul(axis.r)
    const node10 = axis.b.mul(rotateSin)
    const node11 = node2.mul(axis.g)
    const node12 = node2.mul(axis.b)
    const node13 = axis.r.mul(rotateSin)
    const node14 = node3.mul(axis.r)
    const node15 = axis.g.mul(rotateSin)
    const node16 = node3.mul(axis.g)
    const node17 = axis.r.mul(rotateSin)
    const node18 = node3.mul(axis.b)
    const node19 = node4.add(rotateCos)
    const node20 = node5.sub(node6)
    const node21 = node7.add(node8)
    const node22 = node9.add(node10)
    const node23 = node11.add(rotateCos)
    const node24 = node12.sub(node13)
    const node25 = node14.sub(node15)
    const node26 = node16.add(node17)
    const node27 = rotateCos.add(node18)
    const node28 = vec3(node19,node20,node21)
    const node29 = vec3(node22,node23,node24)
    const node30 = vec3(node25,node26,node27)
    const node31 = mat3(node28,node29,node30).mul(inValue)
    return node31
})

